### ISSUE TITLE
A few issues...

### ISSUE THREAD

**Issue by johnnovak** [onelivesleft/simple_parseopt#1]
Any interest in developing this further? It seems like a useful and interesting library.

A couple of issues I ran into:

- I think if the command name hasn't been specified, it should just use the name of the executable instead of defaulting to `simple_parseopt`
- You can specify an uppercase single-letter alias (it compiles), but at runtime it's impossible to use them (you'll get a "no such parameter" error)
- Camel cased parameters names are lowercased, this is undesirable
- Dash separated long parameter names are nice (e.g. `--big-endian`), currently it's not really possible to use these. E.g. the following

```
 bigEndian    = false {.alias("b", "big-endian"), info("force big-endian output").}
```

will result in these generated parameter names (we don't need `--bigendian`)

```
--bigendian, -b, --big-endian    force big-endian output
```

Ideally, you could use underscores in the variable name that would get converted to dashes (`big_endian` -> `--big-endian`), and also we need an ability to completely override the long name with something else and ignore the variable name.

- I think the config option chaining with dots is ridiculous :) It gets completely unreadable quickly, and you end up with waaaaaay too long lines with many options.
- The pragma approach is alsoa bit questionable, it would be nicer to have a format like this (shouldn't be too hard to achieve it with macros):

```nim
let (opts, supplied) = getOptionsAndSupplied:
  show:
    default = false,
    info = "show chunk tree"
  recreate:
    default = false, alias = "r", info = "recreate file"
```

EDIT: typos

**Comment by onelivesleft** [comment]
Yes, will look into your feedback

**Comment by onelivesleft** [comment]
Thank you very much ; this is excellent feedback. I've updated to v1.1.0 which addresses some of your issues:

* Command name not displaying was a bug, should be fixed.
* The fields are now case sensitive.
* If you include `_` in your field name it will translate to `-` in the parameter name.  You may later refer to those fields using camelCase (as it's nim).  
* Config option chaining is optional, if you don't like it then simply call each config method as normal.

**Comment by johnnovak** [comment]
Great, thanks! I'll give it a go in a few days!
